export function isValidDate(date: string) {
  return !Number.isNaN(new Date(date));
}

export function localInputToUTC(value: string): UTCString {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    throw new Error(`Invalid datetime-local value: ${value}`);
  }

  return date.toISOString();
}

export function UTCToLocalInput(value: UTCString): string {
  const date = new Date(value);

  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");

  return `${year}-${month}-${day}T${hours}:${minutes}`;
}

export function now(): UTCString {
  // TODO: when time travel is on, alert user once
  // Uncomment the following when testing/debugging to "travel in time"
  //
  // const d = new Date();
  // d.setUTCDate(d.getUTCDate() + 1); // Adds 1 day
  // return d.toISOString();

  return new Date().toISOString();
}

export function startOfUTCDay(time: UTCString): UTCDateString {
  const d = new Date(time);
  d.setUTCHours(0, 0, 0, 0);
  return d.toISOString();
}

export function nextUTCDay(day: UTCDateString): UTCDateString {
  const d = new Date(day);
  d.setUTCDate(d.getUTCDate() + 1);
  return startOfUTCDay(d.toISOString());
}

type DateParts = {
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
};

// returns the UTC string when the local time is equal to the given UTC string
export function utcWithSameLocalTime(
  utcString: UTCString,
  timeZone: TimezoneString,
  isDstBroken: boolean = false,
): UTCString {
  if (isDstBroken) return utcWithSameLocalTimeBroken(utcString, timeZone);

  const input = new Date(utcString);

  if (Number.isNaN(input.getTime())) {
    throw new Error(`Invalid UTC date: ${utcString}`);
  }

  // Extract the UTC wall-clock components.
  const target: DateParts = {
    year: input.getUTCFullYear(),
    month: input.getUTCMonth() + 1,
    day: input.getUTCDate(),
    hour: input.getUTCHours(),
    minute: input.getUTCMinutes(),
    second: input.getUTCSeconds(),
  };

  // Initial guess: interpret the wall-clock time as UTC.
  let guess = new Date(
    Date.UTC(
      target.year,
      target.month - 1,
      target.day,
      target.hour,
      target.minute,
      target.second
    )
  );

  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone,
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    hour12: false,
  });

  function getParts(date: Date): DateParts {
    const parts = formatter.formatToParts(date);

    const obj: Partial<DateParts> = {};

    for (const part of parts) {
      switch (part.type) {
        case "year":
        case "month":
        case "day":
        case "hour":
        case "minute":
        case "second":
          obj[part.type] = Number(part.value);
          break;
      }
    }

    if (
      obj.year === undefined ||
      obj.month === undefined ||
      obj.day === undefined ||
      obj.hour === undefined ||
      obj.minute === undefined ||
      obj.second === undefined
    ) {
      throw new Error("Failed to extract date parts.");
    }

    return obj as DateParts;
  }

  // Usually converges in one iteration, but repeat to handle DST edges.
  for (let i = 0; i < 3; i++) {
    const local = getParts(guess);

    const actualUtc = Date.UTC(
      local.year,
      local.month - 1,
      local.day,
      local.hour,
      local.minute,
      local.second
    );

    const desiredUtc = Date.UTC(
      target.year,
      target.month - 1,
      target.day,
      target.hour,
      target.minute,
      target.second
    );

    guess = new Date(guess.getTime() + (desiredUtc - actualUtc));
  }

  return guess.toISOString();
}

// In the past there was a problem in the function that gets a UTCString for local time
// It didn't take DST into account
// Because of it, the deadlines of tasks generated by habits was at 02:00 during DST
// If i just fix it, if the user completed such a task after the midnight, it will no longer be considered completed
// because it is after the deadline with the new function
// That can cause unexpected consequences, and that's why we'll use the old broken function for old events
function utcWithSameLocalTimeBroken(time: UTCString, timezone: TimezoneString): UTCString {
  const date = new Date(time);

  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  }).formatToParts(date);

  const get = (type: string) =>
    parts.find(p => p.type === type)!.value;

  const localAsUTC = new Date(
    Date.UTC(
      Number(get("year")),
      Number(get("month")) - 1,
      Number(get("day")),
      Number(get("hour")),
      Number(get("minute")),
      Number(get("second")),
    )
  );

  return localAsUTC.toISOString();
}

export function getWeekdayOfDate(date: UTCDateString): number {
  if (!isValidDate(date)) throw new Error(`Invalid UTC string: ${date}`);

  // Convert to: 0 = Monday ... 6 = Sunday
  return (new Date(date).getUTCDay() + 6) % 7;
}

export function getTimezone() {
  return Intl.DateTimeFormat().resolvedOptions().timeZone;
}
